@startuml
interface Repository
interface CrudRepository<T, ID> {
    save(S entity) : S
    saveAll(Iterable<S extends T> entities) : Iterable<S extends T>
    findById(ID id) : Optional<T>
    existsById(ID id) : boolean
    findAll() : Iterable<T>
    findAllById(Iterable<ID> ids) : Iterable<T>
    count() : long
    deleteById(ID id) : void
    delete(T entity) : void
    deleteAllById(Iterable<? extends ID> ids) : void
    deleteAll(Iterable<? extends T> entities) : void
    deleteAll() : void
}
interface PagingAndSortingRepository<T, ID> {
    findAll(Sort sort) : Iterable<T>
    findAll(Pageable pageable) : Page<T>
}
interface JpaRepository<T, ID> {
    findAll() : List<T>
    findAll(Sort sort) : List<T>
    findAllById(Iterable<ID> ids) : List<T>
    saveAll(Iterable<S extends T> entities) : List<S extends T>
    flush() : void
    saveAndFlush(S entity) : S
    saveAllAndFlush(Iterable<S extends T> entities) : List<S extends T>
    deleteAllInBatch(Iterable<T> entities) : void
    deleteAllByIdInBatch(Iterable<ID> ids) : void
    deleteAllInBatch() : void
    getOne(ID id) : T
    getById(ID id) : T
    findAll(Example<S extends T> example) : List<S extends T>
    findAll(Example<S extends T> example, Sort sort) : List<S extends T>
}

Repository <|-down- CrudRepository
CrudRepository <|-down- PagingAndSortingRepository
JpaRepository -up-|> CrudRepository
JpaRepository -up-|> PagingAndSortingRepository
@enduml